baseURL = "/senior-project/guide/"
languageCode = "en-us"
title = "Senior Project Write-Up"
theme = "book"

[params]
    enableGitInfo = true
    enableRobotsTXT = true
    buildDrafts = true
    buildExpired = false
    buildFuture = false

    # For "book" theme
    BookSection = '*'
    BookToC = true
    BookTheme = 'auto' # one of ('light', 'dark', 'auto')
    BookRepo = 'https://gitlab.com/kedwinchen/edu.calpoly.cpe.senior-project.guide'
    # BookEditPath = '-/edit/latest-stable'
    BookEditPath = '-/blob/latest-stable'

[minify]
    minifyOutput = true
