baseURL = "/senior-project/guide/"
languageCode = "en-us"
title = "Senior Project Write-Up"
theme = "techdoc"

[params]
    menu_style = "open-menu"
    dateformat = "Monday, 02 Jan 2006 15:04:05 MST"
